/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni202557201015;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.JOptionPane;
import java.awt.CardLayout;

/**
 *
 * @author HP
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    private CardLayout cardLayout;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        inisiasiPanel();
    }
    void inisiasiPanel(){
        cardLayout =(CardLayout)panelContent.getLayout();
        panelContent.add(new panelDashboard(),"Dasboard");
        panelContent.add(new panelJurusan(),"Jurusan");
        panelContent.add(new panelGuru(),"Guru");
        panelContent.add(new panelKelas(),"Kelas");
        panelContent.add(new panelSiswa(),"Siswa");
        panelContent.add(new panelAbout(),"About");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSideBar = new javax.swing.JPanel();
        Aloomni = new javax.swing.JLabel();
        bDashboard = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Alumni");
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        PanelSideBar.setBackground(new java.awt.Color(0, 153, 255));
        PanelSideBar.setPreferredSize(new java.awt.Dimension(200, 600));

        Aloomni.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        Aloomni.setForeground(new java.awt.Color(255, 255, 255));
        Aloomni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Aloomni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-graduate-40.png"))); // NOI18N
        Aloomni.setText("Aloomni");

        bDashboard.setBackground(new java.awt.Color(0, 0, 204));
        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-dashboard-20 (1).png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setBorderPainted(false);
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.addActionListener(this::bDashboardActionPerformed);

        bJurusan.setBackground(new java.awt.Color(0, 0, 204));
        bJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-department-20.png"))); // NOI18N
        bJurusan.setText("Jurusan");
        bJurusan.setBorderPainted(false);
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.addActionListener(this::bJurusanActionPerformed);

        bGuru.setBackground(new java.awt.Color(0, 0, 204));
        bGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-teacher-20.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setBorderPainted(false);
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.addActionListener(this::bGuruActionPerformed);

        bKelas.setBackground(new java.awt.Color(0, 0, 204));
        bKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-class-20.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setBorderPainted(false);
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.addActionListener(this::bKelasActionPerformed);

        bSiswa.setBackground(new java.awt.Color(0, 0, 204));
        bSiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-user-20.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setBorderPainted(false);
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.addActionListener(this::bSiswaActionPerformed);

        bAbout.setBackground(new java.awt.Color(0, 0, 204));
        bAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-about-20.png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setBorderPainted(false);
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.addActionListener(this::bAboutActionPerformed);

        bLogout.setBackground(new java.awt.Color(0, 0, 204));
        bLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni202557201015/img/icons8-logout-20.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setBorderPainted(false);
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.addActionListener(this::bLogoutActionPerformed);

        javax.swing.GroupLayout PanelSideBarLayout = new javax.swing.GroupLayout(PanelSideBar);
        PanelSideBar.setLayout(PanelSideBarLayout);
        PanelSideBarLayout.setHorizontalGroup(
            PanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSideBarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Aloomni, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(bDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelSideBarLayout.setVerticalGroup(
            PanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Aloomni, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        getContentPane().add(PanelSideBar, java.awt.BorderLayout.LINE_START);

        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "Jurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "Guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "Siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "Dashboard");
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "Kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        cardLayout.show(panelContent, "About");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int pilihan =JOptionPane.showConfirmDialog(
        null,
                "Apakah Anda Yakin Ingin Keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        
        switch(pilihan){
            case JOptionPane.YES_OPTION:
            dispose();
            new homee().setVisible(true);
            break;
        case JOptionPane.NO_OPTION:
            break;
        default:
            break;
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            UIManager.put("Button.borderWidth", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aloomni;
    private javax.swing.JPanel PanelSideBar;
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JPanel panelContent;
    // End of variables declaration//GEN-END:variables
}
