/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package alumni202557201015;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



/**
 *
 * @author HP
 */
public class panelDashboard extends javax.swing.JPanel {
    
    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() {
        initComponents();
        inisiasiPanel();
    }
    void inisiasiPanel(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242), 20));
        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jPanel2.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel3.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jumlah Jurusan");
        jLabel1.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel1.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(46, 35));
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("JJ");
        jLabel2.setMaximumSize(new java.awt.Dimension(124, 42));
        jLabel2.setMinimumSize(new java.awt.Dimension(124, 42));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel2);

        jPanel4.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel5.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(0, 102, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Jumlah Guru");
        jLabel3.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel3.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(46, 35));
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JG");
        jLabel4.setMaximumSize(new java.awt.Dimension(124, 42));
        jLabel4.setMinimumSize(new java.awt.Dimension(124, 42));
        jLabel4.setOpaque(true);
        jLabel4.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel5.add(jLabel4, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel4);

        jPanel6.setLayout(new java.awt.GridLayout());

        jPanel7.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel8.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setBackground(new java.awt.Color(0, 102, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Jumlah Kelas");
        jLabel5.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel5.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(46, 35));
        jPanel8.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("JK");
        jLabel6.setMaximumSize(new java.awt.Dimension(124, 42));
        jLabel6.setMinimumSize(new java.awt.Dimension(124, 42));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel8.add(jLabel6, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel6.add(jPanel7);

        jPanel1.add(jPanel6);

        jPanel9.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        jPanel14.setLayout(new java.awt.GridLayout());

        jPanel15.setMinimumSize(new java.awt.Dimension(200, 150));
        jPanel15.setPreferredSize(new java.awt.Dimension(200, 150));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setMinimumSize(new java.awt.Dimension(766, 150));
        jPanel16.setPreferredSize(new java.awt.Dimension(766, 150));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(0, 102, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Jumlah Siswa");
        jLabel11.setMaximumSize(new java.awt.Dimension(46, 35));
        jLabel11.setMinimumSize(new java.awt.Dimension(46, 35));
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(46, 35));
        jPanel16.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("JS");
        jLabel12.setMaximumSize(new java.awt.Dimension(124, 42));
        jLabel12.setMinimumSize(new java.awt.Dimension(124, 42));
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(124, 42));
        jPanel16.add(jLabel12, java.awt.BorderLayout.CENTER);

        jPanel15.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        jPanel14.add(jPanel15);

        jPanel9.add(jPanel14);

        jPanel1.add(jPanel9);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
